-- Esquema PostgreSQL de RemesasVE (equivalente al de SQLite, ya consolidado
-- con todas las columnas que en SQLite se añadían por migración incremental).
-- Diferencias de dialecto: REAL → DOUBLE PRECISION, DATETIME → TIMESTAMPTZ,
-- CURRENT_TIMESTAMP → now(), id autoincremental → GENERATED ... AS IDENTITY.

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  nombre TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  telefono TEXT,
  rut TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  kyc_estado TEXT NOT NULL DEFAULT 'no_iniciado' CHECK (kyc_estado IN ('no_iniciado','en_revision','verificado','rechazado')),
  kyc_nivel INTEGER NOT NULL DEFAULT 1,
  fecha_nacimiento TEXT,
  direccion TEXT,
  ciudad TEXT,
  tipo_documento TEXT,
  numero_documento TEXT,
  is_admin INTEGER NOT NULL DEFAULT 0,
  totp_secret TEXT,
  totp_enabled INTEGER NOT NULL DEFAULT 0,
  email_verificado INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cuentas_origen (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  banco TEXT NOT NULL,
  tipo_cuenta TEXT NOT NULL,
  numero_cuenta TEXT NOT NULL,
  titular TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS destinatarios (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('banco','pago_movil')),
  banco TEXT,
  numero_cuenta TEXT,
  cedula TEXT,
  telefono TEXT,
  favorito INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS transferencias (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  cuenta_origen_id TEXT NOT NULL REFERENCES cuentas_origen(id),
  destinatario_id TEXT NOT NULL REFERENCES destinatarios(id),
  monto_clp DOUBLE PRECISION NOT NULL,
  tasa_usd_clp DOUBLE PRECISION NOT NULL,
  tasa_usd_ves DOUBLE PRECISION NOT NULL,
  monto_usd DOUBLE PRECISION NOT NULL,
  monto_ves DOUBLE PRECISION NOT NULL,
  comision_clp DOUBLE PRECISION NOT NULL,
  estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','pagado','procesando','completada','fallida','cancelada')),
  referencia TEXT UNIQUE NOT NULL,
  notas_admin TEXT,
  khipu_payment_id TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS transferencia_eventos (
  id TEXT PRIMARY KEY,
  transferencia_id TEXT NOT NULL REFERENCES transferencias(id) ON DELETE CASCADE,
  estado TEXT NOT NULL,
  descripcion TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notificaciones (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL DEFAULT 'info',
  titulo TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  meta TEXT,
  leida INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tasas_cache (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usd_clp DOUBLE PRECISION NOT NULL,
  usd_ves DOUBLE PRECISION NOT NULL,
  fuente TEXT,
  manual INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS configuracion (
  clave TEXT PRIMARY KEY,
  valor TEXT NOT NULL,
  descripcion TEXT,
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admin_log (
  id TEXT PRIMARY KEY,
  admin_id TEXT NOT NULL,
  admin_nombre TEXT,
  accion TEXT NOT NULL,
  entidad TEXT,
  entidad_id TEXT,
  detalle TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS backup_codes (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  usado INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  expira TIMESTAMPTZ NOT NULL,
  usado INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_trans_user ON transferencias(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_notif_user ON notificaciones(user_id, leida);
CREATE INDEX IF NOT EXISTS idx_eventos_trans ON transferencia_eventos(transferencia_id);
CREATE INDEX IF NOT EXISTS idx_admin_log ON admin_log(created_at);
CREATE INDEX IF NOT EXISTS idx_backup_user ON backup_codes(user_id, usado);
CREATE INDEX IF NOT EXISTS idx_tokens ON tokens(tipo, token_hash);
